/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicioUI;

import javax.swing.JOptionPane;

/**
 *
 * @author jacob
 */
public class MiCacharro extends javax.swing.JFrame {

    /**
     * Creates new form miCacharro
     */
    public MiCacharro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVehiculo = new javax.swing.ButtonGroup();
        pnlTipoVehiculo = new javax.swing.JPanel();
        rbtnAutomovil = new javax.swing.JRadioButton();
        rbtnCamioneta = new javax.swing.JRadioButton();
        rbtnCamion = new javax.swing.JRadioButton();
        pnlCaracteristicas = new javax.swing.JPanel();
        cbCaracteristicas = new javax.swing.JComboBox<>();
        pnlAccesorios = new javax.swing.JPanel();
        cbAccesorios = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNuevoPresupuesto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi cacharro: Sistema de presupuestos");

        pnlTipoVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de vehículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".SF NS Text", 0, 14))); // NOI18N

        grupoVehiculo.add(rbtnAutomovil);
        rbtnAutomovil.setText("Automóvil");
        rbtnAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAutomovilActionPerformed(evt);
            }
        });

        grupoVehiculo.add(rbtnCamioneta);
        rbtnCamioneta.setText("Camioneta");
        rbtnCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCamionetaActionPerformed(evt);
            }
        });

        grupoVehiculo.add(rbtnCamion);
        rbtnCamion.setText("Camión");
        rbtnCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCamionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoVehiculoLayout = new javax.swing.GroupLayout(pnlTipoVehiculo);
        pnlTipoVehiculo.setLayout(pnlTipoVehiculoLayout);
        pnlTipoVehiculoLayout.setHorizontalGroup(
            pnlTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoVehiculoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnCamion)
                    .addComponent(rbtnCamioneta)
                    .addComponent(rbtnAutomovil))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlTipoVehiculoLayout.setVerticalGroup(
            pnlTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoVehiculoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rbtnAutomovil)
                .addGap(18, 18, 18)
                .addComponent(rbtnCamioneta)
                .addGap(18, 18, 18)
                .addComponent(rbtnCamion)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Características"));

        cbCaracteristicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico", "Semi-full", "Full equipo" }));
        cbCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaracteristicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCaracteristicasLayout = new javax.swing.GroupLayout(pnlCaracteristicas);
        pnlCaracteristicas.setLayout(pnlCaracteristicasLayout);
        pnlCaracteristicasLayout.setHorizontalGroup(
            pnlCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaracteristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCaracteristicas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCaracteristicasLayout.setVerticalGroup(
            pnlCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCaracteristicasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(cbCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlAccesorios.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesorios"));

        cbAccesorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin accesorios", "Radio básica", "Full radio", "Full radio + LCD-TV", "Full radio + LCD Full", "Full radio + LCD Full + Llantas" }));
        cbAccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccesoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccesoriosLayout = new javax.swing.GroupLayout(pnlAccesorios);
        pnlAccesorios.setLayout(pnlAccesoriosLayout);
        pnlAccesoriosLayout.setHorizontalGroup(
            pnlAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAccesorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAccesoriosLayout.setVerticalGroup(
            pnlAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoriosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cbAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnNuevoPresupuesto.setText("Nuevo presupuesto");
        btnNuevoPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPresupuestoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNuevoPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnNuevoPresupuesto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnSalir))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double automovil = 5000000, camioneta = 8000000, camion = 12000000;
        double valorTotalVehiculo =  0, valorAccesorio = 0, valorCaracteristica = 0;
        int posicionCaracteristica = cbCaracteristicas.getSelectedIndex();
        int posicionAccesorio = cbAccesorios.getSelectedIndex();
        valorCaracteristica += obtenerValorCaracteristicas(posicionCaracteristica);
        valorAccesorio += obtenerValorAccesorio(posicionAccesorio);
        
        if (rbtnAutomovil.isSelected()) {
            valorTotalVehiculo += automovil + valorCaracteristica + valorAccesorio;
            JOptionPane.showMessageDialog(null, "Valor del automóvil: "+(valorTotalVehiculo));
        } else if (rbtnCamioneta.isSelected()) {
            valorTotalVehiculo += camioneta + valorCaracteristica + valorAccesorio;
            JOptionPane.showMessageDialog(null, "Valor de la camioneta: "+(valorTotalVehiculo));
        } else if (rbtnCamion.isSelected()) {
            valorTotalVehiculo += camion + valorCaracteristica + valorAccesorio;
            JOptionPane.showMessageDialog(null, "Valor del camion: "+(valorTotalVehiculo));
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar el tipo de veículo");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void rbtnAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAutomovilActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbtnAutomovilActionPerformed

    private void rbtnCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCamionetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCamionetaActionPerformed

    private void rbtnCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCamionActionPerformed

    private void cbCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaracteristicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCaracteristicasActionPerformed

    private void cbAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccesoriosActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String nombreVehiculo = "";
        String nombreCaracteristica = cbCaracteristicas.getSelectedItem().toString();
        String nombreAccesorio = cbAccesorios.getSelectedItem().toString();
        double automovil = 5000000, camioneta = 8000000, camion = 12000000;
        double valorTotalVehiculo =  0, valorAccesorio = 0, valorCaracteristica = 0;
        int posicionCaracteristica = cbCaracteristicas.getSelectedIndex();
        int posicionAccesorio = cbAccesorios.getSelectedIndex();
        
        if (rbtnAutomovil.isSelected()) {
            nombreVehiculo = "Automóvil";
            valorCaracteristica = obtenerValorCaracteristicas(posicionCaracteristica);
            valorAccesorio = obtenerValorAccesorio(posicionAccesorio);
            valorTotalVehiculo += automovil + valorCaracteristica + valorAccesorio;
            
            JOptionPane.showMessageDialog(null, "Detalle\n"+
                    "\nTipo de vehículo: "+nombreVehiculo+"    Valor: "+automovil+
                    "\nCaracterística    : "+nombreCaracteristica+"    Valor: "+valorCaracteristica+
                    "\nAccesorio          : "+nombreAccesorio+"    Valor: "+valorAccesorio+
                    "\n\nValor total del vehículo: "+(valorTotalVehiculo));
        } else if (rbtnCamioneta.isSelected()) {
            nombreVehiculo = "Camioneta";
            valorCaracteristica = obtenerValorCaracteristicas(posicionCaracteristica);
            valorAccesorio = obtenerValorAccesorio(posicionAccesorio);
            valorTotalVehiculo += camioneta + valorCaracteristica + valorAccesorio;
            
            JOptionPane.showMessageDialog(null, "Detalle\n"+
                    "\nTipo de vehículo: "+nombreVehiculo+"    Valor: "+camioneta+
                    "\nCaracterística    : "+nombreCaracteristica+"    Valor: "+valorCaracteristica+
                    "\nAccesorio          : "+nombreAccesorio+"    Valor: "+valorAccesorio+
                    "\n\nValor total del vehículo: "+(valorTotalVehiculo));
        } else if (rbtnCamion.isSelected()) {
            nombreVehiculo = "Camión   ";
            valorCaracteristica = obtenerValorCaracteristicas(posicionCaracteristica);
            valorAccesorio = obtenerValorAccesorio(posicionAccesorio);
            valorTotalVehiculo += camion + valorCaracteristica + valorAccesorio;
            
            JOptionPane.showMessageDialog(null, "Detalle\n"+
                    "\nTipo de vehículo: " + nombreVehiculo + "    Valor: "+camion +
                    "\nCaracterística    : " + nombreCaracteristica + "    Valor: "+valorCaracteristica+
                    "\nAccesorio          : " + nombreAccesorio + "    Valor: "+valorAccesorio+
                    "\n\nValor total del vehículo: "+(valorTotalVehiculo));
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar el tipo de vehículo");
        }
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPresupuestoActionPerformed
        grupoVehiculo.clearSelection();
        cbCaracteristicas.setSelectedIndex(0);
        cbAccesorios.setSelectedIndex(0);
    }//GEN-LAST:event_btnNuevoPresupuestoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    public int obtenerValorCaracteristicas(int posicionCaracteristica) {
        int valorCaracteristica = 0;
        
        switch(posicionCaracteristica) {
            case 0:
                valorCaracteristica += 0;
                break;
            case 1: 
                valorCaracteristica += 500000;
                break;
            case 2:
                valorCaracteristica += 1000000;
                break;
        }
        
        return valorCaracteristica;
    }
    
    public int obtenerValorAccesorio(int posicionAccesorio) {
        int valorCaracteristica = 0;
        
        switch(posicionAccesorio) {
            case 0:
                valorCaracteristica += 0;
                break;
            case 1:
                valorCaracteristica += 60000;
                break;
            case 2:
                valorCaracteristica += 100000;
                break;
            case 3:
                valorCaracteristica += 150000;
                break;
            case 4: 
                valorCaracteristica += 200000;
                break;
            case 5:
                valorCaracteristica += 500000;
                break;
        }
        
        return valorCaracteristica;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCacharro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevoPresupuesto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbAccesorios;
    private javax.swing.JComboBox<String> cbCaracteristicas;
    private javax.swing.ButtonGroup grupoVehiculo;
    private javax.swing.JPanel pnlAccesorios;
    private javax.swing.JPanel pnlCaracteristicas;
    private javax.swing.JPanel pnlTipoVehiculo;
    private javax.swing.JRadioButton rbtnAutomovil;
    private javax.swing.JRadioButton rbtnCamion;
    private javax.swing.JRadioButton rbtnCamioneta;
    // End of variables declaration//GEN-END:variables
}
